name: mcp-job-hunting-copilot

command:
  - python
  - main.py

env:
  - name: LAKEBASE_CONNECTION_STRING
    valueFrom: LAKEBASE_CONNECTION_STRING
  - name: ADZUNA_APP_ID
    valueFrom: ADZUNA_APP_ID
  - name: ADZUNA_APP_KEY
    valueFrom: ADZUNA_APP_KEY
